Edit name command
CS2103AUG2016-F11-C1/addressbook-level3 pull request #1
Opened 2016-09-24 14:18 UTC by ChaseYaoCong

# Add a new command 
* Edit Name command based on index

2016-09-27 19:06 UTC, louietyj requested changes
Write some logic tests?

2016-09-27 19:06 UTC, louietyj commented on src/seedu/addressbook/commands/HelpCommand.java
> +    		+ "\n" + EditNameCommand.MESSAGE_USAGE
Indentation

2016-09-27 19:06 UTC, louietyj commented on src/seedu/addressbook/data/person/Person.java
> +
Spurious newlines

2016-09-27 19:06 UTC, louietyj commented on src/seedu/addressbook/data/person/UniquePersonList.java
> +		if(internalList.size() < index || index <= 0){
Missing spaces

2016-09-27 19:06 UTC, louietyj commented on src/seedu/addressbook/parser/Parser.java
> +    	if(trimSpace(arguments).split(SPACE).length <= 1){
Same

2016-09-27 19:06 UTC, louietyj commented on src/seedu/addressbook/parser/Parser.java
> +    private Command prepareEdit(String arguments) {
Indentation for whole block

2016-09-28 04:12 UTC, ChaseYaoCong commented on src/seedu/addressbook/commands/HelpCommand.java
> +    		+ "\n" + EditNameCommand.MESSAGE_USAGE
fixed.

2016-09-28 04:12 UTC, ChaseYaoCong commented on src/seedu/addressbook/data/person/Person.java
> +
fixed.

2016-09-28 04:12 UTC, ChaseYaoCong commented on src/seedu/addressbook/data/person/UniquePersonList.java
> +		if(internalList.size() < index || index <= 0){
fixed.

2016-09-28 04:12 UTC, ChaseYaoCong commented on src/seedu/addressbook/parser/Parser.java
> +    	if(trimSpace(arguments).split(SPACE).length <= 1){
fixed.

2016-09-28 04:12 UTC, ChaseYaoCong commented on src/seedu/addressbook/parser/Parser.java
> +    private Command prepareEdit(String arguments) {
fixed.

2016-09-28 07:14 UTC, louietyj requested changes
Still pending linting errors.

2016-09-28 07:14 UTC, louietyj commented on src/seedu/addressbook/parser/Parser.java
> +	}
Lines 119-127 still not fixed.

2016-09-28 07:16 UTC, louietyj commented
Wait is addressbook3 gonna be the base for our final Phase C submission? If not screw it just merge.

2016-09-28 07:59 UTC, louietyj commented
Okay apparently not =x

2016-09-28 07:59 UTC, merged